services:
  rabbitmq:
    hostname: chatgpt-movie-rabbitmq
    image: rabbitmq:3.11-management
    environment:
      - RABBITMQ_DEFAULT_USER=chatgpmoviewebadmin
      - RABBITMQ_DEFAULT_PASS=zlpL0xjKYY1iX0j365zoIjz
    volumes:
      - ./service/rabbitmq/data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 10s
      retries: 20

  movie_api:
    build:
      context: ./
      dockerfile: ./service/movieApi/docker/Dockerfile
    environment:
      - UID=${UID}
      - GID=${GID}
    tty: true
    volumes:
      - ./service/movieApi/src:/app
      - chatgpt-movie-rabbitmq-ma-nm:/app/node_modules
    command: sh -c "yarn run start"
    ports:
      - "${MOVIE_API_IP}:${MOVIE_API_PORT}:25673"
    depends_on:
      rabbitmq:
        condition: service_healthy

  movie_engine:
    build:
      context: ./
      dockerfile: ./service/movieEngine/docker/Dockerfile
    tty: true
    volumes:
      - ./service/movieEngine/src:/app
      - chatgpt-movie-rabbitmq-me-nm:/app/node_modules
    command: sh -c "yarn run start"
    depends_on:
      rabbitmq:
        condition: service_healthy

  voicevox:
    image: voicevox/voicevox_engine:cpu-0.21.1
    environment:
      - RUN_MODE=production
    restart: unless-stopped

  chatgpt:
    build:
      context: ./
      dockerfile: ./service/chatgpt/docker/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./service/chatgpt/src:/app
      - chatgpt-movie-rabbitmq-cg-nm:/app/node_modules
    command: sh -c "yarn run start"
    depends_on:
      rabbitmq:
        condition: service_healthy
 
volumes:
  chatgpt-movie-rabbitmq-ma-nm:
  chatgpt-movie-rabbitmq-me-nm:
  chatgpt-movie-rabbitmq-cg-nm:

